apiVersion: v1
name: boring # This value was modified by the initial-setup python script
description: A Helm chart for deploying boring-frontend. # This value was modified by the initial-setup python script
version: 1.0
