apiVersion: v1
name: alexa # This value was modified by the initial-setup python script
description: A Helm chart for deploying alexa-frontend. # This value was modified by the initial-setup python script
version: 1.0
