environment: dev
    
redis_host: master.ngao-nghe-dev-elascache-rep-group.7x8qwo.euc1.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:  
    tag: 87
  replicas: 1

secret:
  redis_pass: automate-all-the-things-dev
