environment: stage

redis_host: master.boring-stage-elascache-rep-group.xmpscn.use1.cache.amazonaws.com

deployment:
  image:
    tag: 0
  replicas: 1

secret:
  redis_pass: automate-all-the-things-stage
