appName: boring # This value was modified by the initial-setup python script

service: backend

port: 3000

deployment:
  labels: {    
    istio: monitor # This label is used by the PodMonitor
  }
  image:
    repository: aclong27/boring-backend # This value was modified by the initial-setup python script
